/**
 * Canonical Officer Crabtree transformations from 'Allo 'Allo!
 *
 * Sources:
 * - Wikipedia / BBC: vowel mangling device (Arthur Bostrom)
 * - alloallo.fandom.com Officer Crabtree page
 * - IMDb tt0086659 quotes
 */
export default {
  meta: {
    name: "canonical",
    label: "Original Crabtree",
    description: "Authentic show malapropisms — good moaning, pissing by the door, etc.",
    documented: true,
  },

  wholeWords: {
    morning: "moaning",
    evening: "moaning",
    passing: "pissing",
    pass: "piss",
    passed: "pissed",
    drop: "drip",
    shot: "shat",
    shots: "shats",
    gun: "goon",
    party: "potty",
    news: "nose",
    worry: "weary",
    possible: "pissable",
    police: "poloce",
    policeman: "poloceman",
    airmen: "earmen",
    airman: "earman",
    cell: "sill",
    dark: "dick",
    duty: "dirty",
    bag: "bog",
    cake: "kak",
    think: "thonk",
    wise: "woose",
    town: "tin",
    late: "loot",
    bomber: "bummer",
    map: "mop",
    bicycle: "bersicle",
    electricity: "electrocity",
    radio: "roodio",
    pedal: "piddle",
    naples: "nipples",
    winking: "wonking",
    wink: "wonk",
    winked: "wonked",
    knickers: "knockers",
    cafe: "coffee",
    lamp: "limp",
    tarts: "tits",
    tart: "tit",
    table: "tible",
    window: "winedow",
    duck: "dick",
    paying: "peeing",
    pay: "pee",
    banging: "bonging",
    bang: "bong",
    bell: "bill",
    back: "bock",
    passage: "pissage",
    distance: "dostance",
    mother: "mither",
    wrinkled: "wronkled",
    haggard: "higgard",
    hitler: "hotler",
    flick: "flock",
    smallhausen: "smellhorsen",
    resistance: "resist-once",
    acquired: "accqo-aired",
    bomb: "bum",
    bombs: "bums",
    railway: "whaleway",
    bridge: "brodge",
    message: "massage",
    fracture: "frature",
    compound: "compost",
    british: "brotish",
    agent: "urgent",
    force: "farce",
    pumps: "pimps",
    pump: "pimp",
    spanner: "spinner",
    rene: "ronnie",
    rené: "ronnie",
    pissoir: "ponsoir",
    pissoire: "ponsoire",
    french: "fronch",
    notebook: "newt berk",
    notebooks: "newt berks",
    creek: "crick",
    paddle: "piddle",
    look: "leak",
    six: "sox",
    way: "wee",
    hit: "hot",
    water: "wata",
    explode: "ex-plod",
    heil: "hole",
    clock: "cluck",
    winding: "wind-eeng",
    stunned: "stuned",
    falling: "fail-eeng",
    pipe: "poop",
    place: "plase",
    pork: "poron",
    channel: "channal",
    plane: "plan",
    motor: "mot",
    moped: "moa",
    power: "powa",
    pissed: "possed",
    louise: "loo-woes",
    hand: "hind",
    hands: "hinds",
    long: "lung",
    peace: "piss",
    die: "do",

    // From Arthur Bostrom's "Good Moaning France!" and the show corpus.
    fish: "fosh",
    chip: "chop",
    egg: "ogg",
    scramble: "scrimble",
    frog: "frig",
    leg: "log",
    please: "ploose",
    have: "hov",
    copy: "kippy",
    daily: "dooly",
    newspaper: "nosepooper",
    newspapers: "nosepoopers",
    language: "longwodge",
    phrase: "phrose",
    phrases: "phroses",
    book: "berk",
    books: "berks",
    greeting: "grooting",
    disguise: "disgeese",
    able: "oble",
    about: "aboot",
    freedom: "frodom",
    driven: "droven",
    drunk: "droonk",
    men: "min",
    wire: "wier",
    workmen: "wickmen",
    drain: "droon",
    nut: "nit",
    bottle: "bittle",
    knee: "knick",
    knicker: "knocker",
    gift: "goft",
    spare: "spear",
    plan: "plin",
    disease: "disk ease",
    week: "work",
    day: "die",
    seal: "soil",
    fall: "fail",
  },

  phrases: [
    { from: "good morning", to: "good moaning", priority: 400 },
    { from: "good evening", to: "good moaning", priority: 390 },
    { from: "good night", to: "good moaning", priority: 390 },
    { from: "god morning", to: "good moaning", priority: 390 },

    {
      from: "i was passing by the door, and i thought i would drop in",
      to: "i was pissing by the door, and i thought i would drip in",
      priority: 385,
    },
    {
      from: "i was passing by the door and i thought i would drop in",
      to: "i was pissing by the door and i thought i would drip in",
      priority: 385,
    },
    { from: "i thought i would drop in", to: "i thought i would drip in", priority: 384 },
    { from: "i was passing by the door", to: "i was pissing by the door", priority: 380 },
    { from: "i was passing by", to: "i was pissing by", priority: 380 },

    {
      from: "i was passing by the door, when i heard two shots. you are holding in your hand a smoking gun; you are clearly the guilty party",
      to: "i was pissing by the door, when i heard two shats. you are holding in your hind a smoking goon; you are clearly the guilty potty",
      priority: 395,
    },
    {
      from: "i was passing by the door when i heard two shots. you are holding in your hand a smoking gun; you are clearly the guilty party",
      to: "i was pissing by the door when i heard two shats. you are holding in your hind a smoking goon; you are clearly the guilty potty",
      priority: 395,
    },
    { from: "when i heard two shots", to: "when i heard two shats", priority: 380 },
    { from: "when i heard a shot", to: "when i heard a shat", priority: 380 },
    {
      from: "i was passing by the door when i heard a shot",
      to: "i was pissing by the door when i heard a shat",
      priority: 380,
    },
    { from: "smoking gun", to: "smoking goon", priority: 380 },
    { from: "guilty party", to: "guilty potty", priority: 380 },
    { from: "holding in your hand", to: "holding in your hind", priority: 370 },
    { from: "holding in your hands", to: "holding in your hinds", priority: 370 },

    {
      from: "there is obviously no peace for the wicked",
      to: "there is obviously no piss for the wicked",
      priority: 390,
    },
    { from: "no peace for the wicked", to: "no piss for the wicked", priority: 385 },
    { from: "my lips are sealed", to: "my lips are soiled", priority: 385 },

    { from: "good news", to: "good nose", priority: 370 },
    { from: "bad news", to: "bad nose", priority: 370 },
    { from: "do not worry", to: "do not weary", priority: 370 },
    { from: "do not worry rene", to: "do not weary ronnie", priority: 370 },
    { from: "as soon as possible", to: "as soon as pissable", priority: 370 },
    { from: "police station", to: "poloce station", priority: 370 },
    { from: "police notebooks", to: "poloce newt berks", priority: 370 },
    { from: "british airmen", to: "brotish earmen", priority: 370 },
    { from: "in the cell", to: "in the sill", priority: 370 },
    { from: "take a look", to: "take a leak", priority: 370 },
    { from: "have a map", to: "have a mop", priority: 370 },
    { from: "dark night", to: "dick night", priority: 370 },
    { from: "back passage", to: "bock pissage", priority: 370 },
    { from: "my duty", to: "my dirty", priority: 370 },
    { from: "in my bag", to: "in my bog", priority: 370 },
    { from: "have a cake", to: "have a kak", priority: 370 },
    { from: "i think it would be wise", to: "i thonk it would be woose", priority: 360 },
    { from: "left town", to: "left tin", priority: 360 },
    { from: "too late", to: "too loot", priority: 360 },
    { from: "on the way", to: "on the wee", priority: 360 },
    {
      from: "the bomber is already on the way",
      to: "the bummer is already on the wee",
      priority: 360,
    },
    { from: "british air force", to: "brotish air farce", priority: 360 },
    { from: "dropped their bombs", to: "dropped their bums", priority: 360 },
    { from: "direct hit", to: "direct hot", priority: 360 },
    { from: "hit on the pumps", to: "hot on the pimps", priority: 360 },
    { from: "table for two", to: "tible for two", priority: 360 },
    { from: "by the window", to: "by the winedow", priority: 360 },
    { from: "long distance duck", to: "lung-dostance dick", priority: 360 },
    { from: "long distance", to: "lung-dostance", priority: 350 },
    {
      from: "who is paying for the pissoir",
      to: "who is peeing for the ponsoir",
      priority: 360,
    },
    { from: "who is paying", to: "who is peeing", priority: 350 },
    { from: "half past six", to: "half pissed sox", priority: 360 },
    { from: "stop banging the bell", to: "stop bonging the bill", priority: 360 },
    {
      from: "will you please stop banging the bell",
      to: "will you please stop bonging the bill",
      priority: 360,
    },
    { from: "heil hitler", to: "hole hotler", priority: 360 },
    { from: "herr flick", to: "herr flock", priority: 360 },
    { from: "von smallhausen", to: "von smellhorsen", priority: 360 },
    { from: "see naples and die", to: "see nipples and do", priority: 360 },
    { from: "as they say see naples and die", to: "as they say see nipples and do", priority: 360 },
    { from: "i was raised in naples", to: "i was raised in nipples", priority: 360 },
    { from: "raised in naples", to: "raised in nipples", priority: 360 },
    { from: "i was winking at you", to: "i was wonking at you", priority: 360 },
    {
      from: "outside the cafe under the lamp post",
      to: "outside the coffee under the limp post",
      priority: 350,
    },
    { from: "couple of tarts", to: "couple of tits", priority: 360 },
    { from: "mother in law", to: "mither in loo", priority: 360 },
    { from: "more wrinkled and haggard", to: "more wronkled and higgard", priority: 360 },
    { from: "grandfather clock", to: "grandfather cluck", priority: 350 },
    { from: "compound fracture", to: "compost frature", priority: 350 },
    {
      from: "the resistance have acquired a bomb",
      to: "the resist-once have accqo-aired a bum",
      priority: 350,
    },
    {
      from: "resistance have acquired a bomb",
      to: "resist-once have accqo-aired a bum",
      priority: 350,
    },
    { from: "explode the railway bridge", to: "ex-plod the whaleway brodge", priority: 350 },
    {
      from: "they are going to explode the railway bridge",
      to: "they are going to ex-plod the whaleway brodge",
      priority: 355,
    },
    { from: "they will take this spanner", to: "they will take this spinner", priority: 350 },
    {
      from: "get your hands on some girls knickers",
      to: "get your hinds on some girls knockers",
      priority: 350,
    },
    { from: "up the creek without a paddle", to: "up the crick without a piddle", priority: 350 },
    { from: "the policeman cometh", to: "the poloceman cometh", priority: 350 },
    { from: "produce the electricity", to: "produce the electrocity", priority: 340 },
    { from: "electricity for the radio", to: "electrocity for the roodio", priority: 340 },
    { from: "pedal in your", to: "piddle in your", priority: 340 },
    { from: "as pissed as a newt", to: "as possed as a newt", priority: 340 },
    {
      from: "return them to you as soon as possible",
      to: "return them to you as soon as pissable",
      priority: 340,
    },
    {
      from: "two british airmen in the cell at the police station",
      to: "two brotish earmen in the sill at the poloce station",
      priority: 340,
    },
    { from: "i will go out the back passage", to: "i will go out the bock pissage", priority: 340 },
    { from: "i have my duty to do", to: "i have my dirty to do", priority: 340 },
    { from: "pass off", to: "piss off", priority: 340 },
  ],
};
