/**
 * General English malapropisms in Crabtree's style:
 * one vowel/consonant nudge so the word becomes a *different* English word,
 * preferably innuendo — not a fake accent, not random hyphenation.
 */
export const core = {
  wholeWords: {
    annually: "anally",
    annual: "anal",
    analysis: "anal-ysis",
    neutron: "newton",
    source: "sauce",
    sources: "sauces",
    facility: "faecility",
    petabyte: "peterbyte",
    petabytes: "peterbytes",
    gigabyte: "gigglebyte",
    gigabytes: "gigglebytes",
    streaming: "steaming",
    stream: "steam",
    hour: "whore",
    hours: "whores",
    image: "homage",
    images: "homages",
    second: "sexond",
    seconds: "sexonds",
    generate: "genitrate",
    generates: "genitrates",
    order: "odour",
    orders: "odours",
    magnitude: "maggotude",
    decade: "decayed",
    manual: "manure",
    stagger: "swagger",
    detector: "defector",
    detectors: "defectors",
    backlog: "bocklog",
    million: "melon",
    millions: "melons",
    important: "impotent",
    public: "pubic",
    election: "erection",
    elections: "erections",
    section: "sexion",
    sections: "sexions",
    fact: "fart",
    facts: "farts",
    issue: "tissue",
    issues: "tissues",
    nuclear: "new-clear",
    particle: "part-tickle",
    particles: "part-tickles",
    publication: "pubication",
    publications: "pubications",

    // Swaps that land on a real, worse word — the best kind.
    organism: "orgasm",
    organisms: "orgasms",
    substitute: "prostitute",
    unfortunate: "unfartunate",
    unfortunately: "unfartunately",
    university: "uniperversity",
    develop: "devilop",
    development: "devilopment",
    movement: "moovement",
    movements: "moovements",
    father: "farter",
    fathers: "farters",
    sheet: "shit",
    sheets: "shits",
    beach: "bitch",
    beaches: "bitches",
    cork: "cock",
    corks: "cocks",
    button: "bottom",
    buttons: "bottoms",
    walk: "wank",
    walks: "wanks",
    walked: "wanked",
    walking: "wanking",
    sit: "shit",
    sits: "shits",
    sitting: "shitting",
    county: "cunty",
    assessment: "arsessment",
    assessments: "arsessments",
    assumption: "arsumption",
    assumptions: "arsumptions",
    constitution: "constipation",
    peninsula: "penisular",
    dictate: "dick-tate",
    dictator: "dick-tator",
    dictators: "dick-tators",
    canal: "anal",
    canals: "anals",
    cologne: "colon",
    mussels: "muscles",
    mussel: "muscle",
    threat: "tit",
    threats: "tits",
    command: "commode",
    commands: "commodes",
    former: "farmer",
    safety: "sassiety",
    aired: "arsed",
    concern: "consarn",
    concerns: "consarns",
    existential: "sexistential",
    humanity: "human-titty",
    government: "gover-mint",
    governments: "gover-mints",
    people: "peeple",
    company: "campany",
    model: "noodle",
    models: "noodles",

    // General essay / argumentative prose. These have to be real-word
    // malapropisms or the layer is a no-op on anything that isn't lab copy.
    human: "hymen",
    brain: "brawn",
    capability: "culpability",
    other: "otter",
    lack: "luck",
    owe: "own",
    dominant: "dormant",
    position: "potion",
    machine: "marine",
    general: "genital",
    intelligence: "inelegance",
    superintelligence: "superinelegance",
    become: "beckon",
    extreme: "intimate",
    gorilla: "guerrilla",
    depend: "deepen",
    action: "auction",
    distinctive: "instinctive",
    power: "powder",
    fate: "fart",
    humankind: "hymenkind",
    information: "inflammation",
    system: "cistern",
    personal: "personnel",
    private: "pirate",
    patient: "patience",
    body: "bawdy",
    history: "hysteria",
    nature: "nurture",
    enemy: "enema",
    current: "currant",
    opinion: "onion",
    decision: "incision",
    effect: "infect",
    study: "sturdy",
    price: "prize",
    large: "lard",
    short: "shirt",
    life: "lift",
    death: "dearth",
    friend: "fiend",
    family: "famine",
    woman: "omen",
    child: "chilled",
    legal: "lewd",
    climate: "climactic",
    new: "gnu",

    // Reverse-mapped from vulgar punchlines: innocent memo-words one nudge away.
    bigger: "bugger",
    batch: "bitch",
    mature: "manure",
    suit: "shit",
    ship: "shit",
    turn: "turd",
    cook: "cock",
    crop: "crap",
    cram: "crap",
    fast: "fart",
    farm: "fart",
    disk: "dick",
    sack: "suck",
    ping: "pong",
    want: "wank",
    bond: "bonk",
    boot: "boob",
    pool: "poop",
    poor: "poop",
    color: "colon",
    colour: "colon",
    grain: "groin",
    ejection: "erection",
    cult: "cunt",
    shut: "shat",
    spot: "snot",
    know: "knob",
    petty: "potty",
    song: "snog",

    // Found with Datamuse sounds-like and related-word lookups.
    bobby: "booby",
    puddle: "piddle",
    boson: "bosom",
    beast: "breast",
    abreast: "a breast",
  },
  phrases: [
    { from: "keep pace", to: "keep paste", priority: 70 },
    { from: "per second", to: "per sexond", priority: 70 },
    { from: "neutron source", to: "newton sauce", priority: 80 },
    { from: "human brain", to: "hymen brawn", priority: 90 },
    { from: "human brains", to: "hymen brawns", priority: 90 },
    { from: "other animals", to: "otter cannibals", priority: 90 },
    { from: "our species", to: "our faeces", priority: 85 },
    { from: "the species", to: "the faeces", priority: 85 },
    { from: "dominant position", to: "dormant potion", priority: 85 },
    { from: "general intelligence", to: "genital inelegance", priority: 90 },
    { from: "machine superintelligence", to: "marine superinelegance", priority: 90 },
  ],
};

export const extra = {
  wholeWords: {
    ten: "tin",
    data: "dater",
    rough: "ruff",
    equivalent: "equivocal",
    video: "vidio",
    exist: "excite",
    upgrade: "upbraid",
    gone: "goon",
    capturing: "capering",
    capture: "caper",
    single: "shingle",
    mean: "moan",
    light: "late",
    pace: "paste",
    paper: "piper",
    figure: "fig-leaf",
    result: "resalt",
    results: "resalts",
    based: "basted",
    small: "smell",
    later: "looter",
    last: "lost",
    first: "thirst",
    great: "grate",
    little: "tittle",
    value: "valve",
    values: "valves",
    measure: "moisture",
    pressure: "pleasure",
    speed: "seed",
    sample: "simple",
    screen: "scream",
    mouse: "moose",
    type: "tape",
    load: "lewd",
    save: "salve",
    test: "taste",
    tests: "tastes",
    run: "rum",
    wait: "wet",
    file: "foil",
    files: "foils",
    title: "tittle",
    letter: "latter",
    school: "stool",
    signal: "seagull",
    signals: "seagulls",
    noise: "nose",
    science: "scents",
    physics: "physiques",
    minister: "minstrel",
    secretary: "sucretary",
    council: "counsel",
    among: "a-moan",
    under: "udder",
    receive: "recede",
    plan: "pan",
    world: "whirled",
    ensure: "insure",
    capable: "copable",
    remain: "re-moan",
    poste: "postie",
    pose: "pooh",
    algorithm: "algorhythm",
    network: "nutwork",
    theory: "theatre",
    evidence: "effluence",
    reason: "raisin",
    question: "questing",
    member: "mammary",
    business: "busyness",
    national: "rational",
    physical: "fiscal",
    mental: "genital",
    thought: "throat",
    future: "suture",
    cancer: "dancer",
    hospital: "hospitable",
    doctor: "doctrine",
    virus: "viscus",
    energy: "enema",
    beyond: "be-yawn",
    control: "console",
    possibly: "passably",
    effort: "a-fart",
    low: "loo",
    law: "loo",
    where: "whore",
    whole: "whore",
    whose: "whore",
    sick: "suck",
    sock: "suck",
    spit: "shit",
    clap: "crap",
    chap: "crap",
    carp: "crap",
    crab: "crap",
    deck: "dick",
    dock: "dick",
    boom: "boob",
    bone: "bonk",
    knot: "knob",
    sham: "shag",
    snow: "snog",
    snug: "snog",
    sulk: "suck",
    groan: "groin",
    fort: "fart",
    fare: "fart",
    pond: "pong",
    prop: "poop",
    botch: "bitch",
    birch: "bitch",
    cant: "cunt",
  },
  phrases: [],
};
