/**
 * General English malapropisms in Crabtree's style:
 * one vowel/consonant nudge so the word becomes a *different* English word,
 * preferably innuendo — not a fake accent, not random hyphenation.
 */
export const core = {
  wholeWords: {
    annually: "anally",
    annual: "anal",
    analysis: "anal-ysis",
    neutron: "newton",
    source: "sauce",
    sources: "sauces",
    facility: "faecility",
    petabyte: "peterbyte",
    petabytes: "peterbytes",
    gigabyte: "gigglebyte",
    gigabytes: "gigglebytes",
    streaming: "steaming",
    stream: "steam",
    hour: "whore",
    hours: "whores",
    image: "homage",
    images: "homages",
    second: "sexond",
    seconds: "sexonds",
    generate: "genitrate",
    generates: "genitrates",
    order: "odour",
    orders: "odours",
    magnitude: "maggotude",
    decade: "decayed",
    manual: "manure",
    stagger: "swagger",
    detector: "defector",
    detectors: "defectors",
    backlog: "bocklog",
    million: "melon",
    millions: "melons",
    important: "impotent",
    public: "pubic",
    election: "erection",
    elections: "erections",
    section: "sexion",
    sections: "sexions",
    fact: "fart",
    facts: "farts",
    issue: "tissue",
    issues: "tissues",
    nuclear: "new-clear",
    particle: "part-tickle",
    particles: "part-tickles",
    publication: "pubication",
    publications: "pubications",

    // Swaps that land on a real, worse word — the best kind.
    organism: "orgasm",
    organisms: "orgasms",
    substitute: "prostitute",
    unfortunate: "unfartunate",
    unfortunately: "unfartunately",
    university: "uniperversity",
    develop: "devilop",
    development: "devilopment",
    movement: "moovement",
    movements: "moovements",
    father: "farter",
    fathers: "farters",
    sheet: "shit",
    sheets: "shits",
    beach: "bitch",
    beaches: "bitches",
    cork: "cock",
    corks: "cocks",
    button: "bottom",
    buttons: "bottoms",
    walk: "wank",
    walks: "wanks",
    walked: "wanked",
    walking: "wanking",
    sit: "shit",
    sits: "shits",
    sitting: "shitting",
    county: "cunty",
    assessment: "arsessment",
    assessments: "arsessments",
    assumption: "arsumption",
    assumptions: "arsumptions",
    constitution: "constipation",
    peninsula: "penisular",
    dictate: "dick-tate",
    dictator: "dick-tator",
    dictators: "dick-tators",
    canal: "anal",
    canals: "anals",
    cologne: "colon",
    mussels: "muscles",
    mussel: "muscle",
    threat: "tit",
    threats: "tits",
    command: "commode",
    commands: "commodes",
    former: "farmer",
    safety: "sassiety",
    aired: "arsed",
    concern: "consarn",
    concerns: "consarns",
    existential: "sexistential",
    humanity: "human-titty",
    government: "gover-mint",
    governments: "gover-mints",
    people: "peeple",
    company: "campany",
    model: "noodle",
    models: "noodles",
  },
  phrases: [
    { from: "keep pace", to: "keep paste", priority: 70 },
    { from: "per second", to: "per sexond", priority: 70 },
    { from: "neutron source", to: "newton sauce", priority: 80 },
  ],
  substrings: [
    { from: "annual", to: "anal", priority: 80 },
    { from: "stream", to: "steam", priority: 70 },
  ],
};

export const extra = {
  wholeWords: {
    ten: "tin",
    data: "dater",
    rough: "ruff",
    equivalent: "equivocal",
    video: "vidio",
    exist: "excite",
    upgrade: "upbraid",
    gone: "goon",
    capturing: "capering",
    capture: "caper",
    single: "shingle",
    mean: "moan",
    light: "late",
    pace: "paste",
    paper: "piper",
    figure: "fig-leaf",
    result: "resalt",
    results: "resalts",
    based: "basted",
    small: "smell",
    later: "looter",
    last: "lost",
    first: "thirst",
    great: "grate",
    little: "tittle",
    value: "valve",
    values: "valves",
    measure: "moisture",
    pressure: "pleasure",
    speed: "seed",
    sample: "simple",
    screen: "scream",
    mouse: "moose",
    type: "tape",
    load: "lewd",
    save: "salve",
    test: "taste",
    tests: "tastes",
    run: "rum",
    wait: "wet",
    file: "foil",
    files: "foils",
    title: "tittle",
    letter: "latter",
    school: "stool",
    signal: "seagull",
    signals: "seagulls",
    noise: "nose",
    science: "scents",
    physics: "physiques",
    minister: "minstrel",
    secretary: "sucretary",
    council: "counsel",
    among: "a-moan",
    under: "udder",
    receive: "recede",
    plan: "pan",
    world: "whirled",
    ensure: "insure",
    capable: "copable",
    remain: "re-moan",
    poste: "postie",
    pose: "pooh",
  },
  phrases: [],
  substrings: [],
};
