/**
 * Weird and wonderful words: swap a plain word for a funny-sounding synonym
 * ("umbrella" -> "bumbershoot", "fuss" -> "kerfuffle", "fat" -> "blubber").
 * Not an accent. Rude is fine.
 *
 * Sources: busuu.com "52 funny-sounding words in English", parade.com "funny words",
 * Merriam-Webster wordplay (cattywampus, taradiddle, codswallop, flapdoodle), and
 * wikiHow's "Funny English Words" (thingamajig, higgledy-piggledy, gogglebox).
 */

function group(minChaos, { wholeWords = {}, phrases = [] }) {
  return {
    wholeWords: Object.fromEntries(
      Object.entries(wholeWords).map(([from, to]) => [from, { to, minChaos }]),
    ),
    phrases: phrases.map((p) => ({ ...p, minChaos })),
  };
}

// Words rare enough in ordinary text that a swap is a treat, not a tic.
const rare = group(0.15, {
  wholeWords: {
    umbrella: "bumbershoot",
    commotion: "hullabaloo",
    uproar: "brouhaha",
    hype: "ballyhoo",
    jargon: "gobbledygook",
    dawdle: "dillydally",
    pamper: "mollycoddle",
    coddle: "mollycoddle",
    deceive: "bamboozle",
    mislead: "hoodwink",
    astonish: "gobsmack",
    amaze: "flabbergast",
    baffle: "flummox",
    perplex: "bumfuzzle",
    tipsy: "sozzled",
    rascal: "scallywag",
    idiot: "nincompoop",
    chatterbox: "flibbertigibbet",
    mixture: "hodgepodge",
    jumble: "hodgepodge",
    rickety: "ramshackle",
    indecisive: "wishy-washy",
    asap: "lickety-split",
    gadget: "doohickey",
    widget: "whatchamacallit",
    zilch: "bupkis",
    stomachache: "collywobbles",
    nausea: "wamble",
    giggle: "titter",
    cuddle: "canoodle",
    flatter: "schmooze",
    hashtag: "octothorpe",
    newbie: "noob",
    novice: "noob",
    klutz: "stumblebum",
    askew: "cattywampus",
    anticlockwise: "widdershins",
    counterclockwise: "widdershins",
    urchin: "ragamuffin",
    youngster: "whippersnapper",
    pontificate: "bloviate",
    prison: "hoosegow",
    mischief: "shenanigans",
    trickery: "skullduggery",
    politician: "snollygoster",
    grumpy: "ornery",
    rowdy: "rambunctious",
    boisterous: "rambunctious",
    hassle: "rigmarole",
    caveman: "troglodyte",
    lawyer: "pettifogger",
    hangover: "crapulence",
    meddler: "kibitzer",
    hypochondriac: "valetudinarian",
    stew: "slumgullion",
    trinket: "frippery",
    adorable: "adorbs",
    flee: "skedaddle",
    "old-fashioned": "fuddy-duddy",
    depart: "absquatulate",
    vanish: "absquatulate",
    linger: "lollygag",
    loiter: "lollygag",
    scamp: "jackanapes",
    brat: "jackanapes",
    rumor: "furphy",
    rumour: "furphy",
    braggart: "cockalorum",
    blowhard: "cockalorum",
    sycophant: "snool",
    toady: "snool",
    shabby: "tatterdemalion",
    ragged: "tatterdemalion",
    eerie: "eldritch",
    spooky: "eldritch",
    clumsy: "lummox",
    gloomy: "lugubrious",
    mournful: "lugubrious",
    dandy: "foppish",
    remarkable: "lollapalooza",
    corker: "doozy",
    whopper: "doozy",
    quarrel: "argy-bargy",
    chatter: "argle-bargle",
    drunkard: "bacchanal",
    slurp: "bibble",
    antic: "baboonery",
    foolishness: "baboonery",
    stubborn: "mumpsimus",
    bizarre: "gonzo",
    cookie: "snickerdoodle",
    karma: "comeuppance",
    gizmo: "doohickey",
    spiel: "mumbo-jumbo",
    hokum: "bunkum",

    // More cupboard words for plain nouns and verbs the first list never reached.
    kitchen: "scullery",
    garden: "allotment",
    rain: "mizzle",
    cat: "moggie",
    dog: "pooch",
    children: "nippers",
    toilet: "privy",
    bathroom: "loo",
    couch: "davenport",
    sofa: "davenport",
    fridge: "icebox",
    refrigerator: "icebox",
    television: "gogglebox",
    tv: "gogglebox",
    phone: "blower",
    sausage: "banger",
    potato: "spud",
    potatoes: "spuds",
    wine: "plonk",
    food: "victuals",
    meal: "nosh",
    tasty: "scrumptious",
    delicious: "scrumptious",
    hungry: "peckish",
    sleepy: "tuckered",
    coward: "poltroon",
    snob: "hoity-toity",
    snobbish: "highfalutin",
    pretentious: "highfalutin",
    grouch: "curmudgeon",
    cranky: "crotchety",
    irritable: "cantankerous",
    teenager: "hobbledehoy",
    scatterbrain: "flibbertigibbet",
    sentimental: "namby-pamby",
    wimp: "milquetoast",
    fickle: "whiffler",
    perfectionist: "fussbudget",
    nitpicker: "fussbudget",
    absurd: "cockamamie",
    fib: "taradiddle",
    drivel: "piffle",
    twaddle: "piffle",
    hogwash: "codswallop",
    malarkey: "balderdash",
    gibberish: "flapdoodle",
    babble: "bosh",
    tomfoolery: "buffoonery",
    hijinks: "monkeyshines",
    prank: "monkeyshine",
    fight: "donnybrook",
    brawl: "donnybrook",
    predicament: "imbroglio",
    talk: "palaver",
    conversation: "confab",
    laugh: "guffaw",
    chuckle: "chortle",
    surprise: "gobsmack",
    bewilder: "bumfuzzle",
    puzzle: "bumfuzzle",
    knife: "snickersnee",
    secret: "hugger-mugger",
    lazy: "lackadaisical",
    picky: "persnickety",
    fussy: "persnickety",
    huge: "brobdingnagian",
    messy: "higgledy-piggledy",
    clutter: "higgledy-piggledy",
    disorder: "pell-mell",
    cash: "dosh",
    stomach: "breadbasket",
    belly: "breadbasket",
    ancient: "antediluvian",
    strange: "rum",
    peculiar: "rum",
    girlfriend: "kicky-wicky",
    wife: "kicky-wicky",
    scheme: "boondoggle",
    excellent: "humdinger",
    wonderful: "humdinger",
    clingy: "barnacle",
    cheat: "bedswerve",
    exhaust: "knacker",
    madam: "bawd",
    mistress: "doxy",
    lover: "doxy",
    celebration: "hootenanny",
    bash: "hootenanny",
    blob: "dollop",
    scoop: "dollop",
    lump: "dollop",
    spoonful: "dollop",
    // Below silly's "thong", so a mild chaos gets the cupboard word instead.
    thing: "thingamajig",
  },
  phrases: [
    { from: "run away", to: "skedaddle", priority: 70 },
    { from: "ran away", to: "skedaddled", priority: 70 },
    { from: "backseat driver", to: "kibitzer", priority: 80 },
    { from: "interval training", to: "fartlek", priority: 80 },
    { from: "division sign", to: "obelus", priority: 80 },
    { from: "book thief", to: "biblioklept", priority: 80 },
    { from: "waste time", to: "lollygag", priority: 70 },
    { from: "wasted time", to: "lollygagged", priority: 70 },
    { from: "just deserts", to: "comeuppance", priority: 80 },
    { from: "catty-corner", to: "cater-cornered", priority: 80 },
    { from: "old man", to: "geezer", priority: 80 },
    { from: "old woman", to: "biddy", priority: 80 },
  ],
});

// Everyday words that would otherwise turn every other sentence into a kerfuffle.
const common = group(0.45, {
  wholeWords: {
    fuss: "kerfuffle",
    nonsense: "poppycock",
    confuse: "discombobulate",
    nothing: "bupkis",
    cute: "cutesy-poo",
    beginner: "noob",
    rubbish: "folderol",
    gossip: "furphy",
    stuff: "gubbins",
    big: "humongous",
    mess: "higgledy-piggledy",
    many: "oodles",
    plenty: "scads",
    money: "spondulicks",
    fine: "tickety-boo",
    okay: "tickety-boo",
    perfect: "tickety-boo",
    problem: "imbroglio",
    head: "noddle",
    mouth: "bazoo",
    odd: "rum",
    ridiculous: "cockamamie",
    fat: "blubber",
    swear: "billingsgate",
  },
  phrases: [
    { from: "a lot", to: "oodles", priority: 70 },
    { from: "lots of", to: "oodles of", priority: 75 },
  ],
});

export default {
  meta: {
    name: "weird",
    label: "Weird words",
    description: "Funny-sounding synonyms — kerfuffle, bumbershoot, gobbledygook",
  },
  wholeWords: { ...rare.wholeWords, ...common.wholeWords },
  phrases: [...rare.phrases, ...common.phrases],
};
