#!/usr/bin/env node
/**
 * Generate src/lib/stress-data.js from the CMU Pronouncing Dictionary: every plain word whose main
 * stress is not on its first syllable, keyed by the syllable that carries it. The vowel layer uses
 * it to leave unstressed syllables alone ("remember" -> "remomber", not "romember").
 *
 *   npm run build:stress   (re-run after upgrading cmu-pronouncing-dictionary)
 */
import { writeFileSync } from "node:fs";
import { dictionary } from "cmu-pronouncing-dictionary";

const bySyllable = new Map();
for (const [word, phones] of Object.entries(dictionary)) {
  // Skips alternate pronunciations ("read(2)") and entries with apostrophes or digits.
  if (!/^[a-z]+$/.test(word)) continue;
  const vowels = phones.split(" ").filter((phone) => /\d$/.test(phone));
  const stressed = vowels.findIndex((phone) => phone.endsWith("1"));
  if (vowels.length < 2 || stressed < 1) continue;
  if (!bySyllable.has(stressed)) bySyllable.set(stressed, []);
  bySyllable.get(stressed).push(word);
}

const syllables = [...bySyllable.keys()].sort((a, b) => a - b);
const body = syllables
  .map((syllable) => `  ${syllable}: "${bySyllable.get(syllable).sort().join(" ")}",`)
  .join("\n");

writeFileSync(
  new URL("../src/lib/stress-data.js", import.meta.url),
  `// Generated by scripts/build-stress.js from the CMU Pronouncing Dictionary. Do not edit.
// Words whose main stress is not on the first syllable, keyed by the stressed syllable (0-based).
export default {
${body}
};
`,
);

const total = syllables.reduce((sum, syllable) => sum + bySyllable.get(syllable).length, 0);
console.log(`wrote ${total} words to src/lib/stress-data.js`);
